auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m

frontend:
  compress_responses: true
  max_outstanding_per_tenant: 4096

query_range:
  align_queries_with_step: true
  split_queries_by_interval: 5m
  cache_results: true
  results_cache:
    cache:
      memcached:
        expiration: 30m
      memcached_client:
        addresses: memcached:11211
        timeout: 200ms
        max_idle_conns: 256

store:
  index_queries_cache_config:
    memcached:
      expiration: 24h
    memcached_client:
      addresses: memcached:11211
      timeout: 200ms
      max_idle_conns: 256

  chunk_cache_config:
    memcached:
      expiration: 2h
    memcached_client:
      addresses: memcached:11211
      timeout: 200ms
      max_idle_conns: 256

chunk_store_config:
  max_look_back_period: 168h

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false

  max_query_parallelism: 64
  max_outstanding_requests_per_tenant: 4096
  query_timeout: 2m
  max_query_length: 12h
  max_query_lookback: 168h

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_chunk_age: 2h
  chunk_idle_period: 30m
  chunk_retain_period: 30s

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
